### ISSUE TITLE
clang-format support

### ISSUE THREAD

**Issue by definelicht** [Galarius/vscode-opencl#10]
Hey,

I have not had luck configuring clang-format as the OpenCL formatter.
The following has not worked for me:
```
"opencl.formatting.name": "clang-format",
"opencl.formatting.args": ["-i"],
```
I'm not getting any errors, it just does not have any effect.
If I run `clang-format -i <filename>` from the terminal it works as expected.

Perhaps this is related to how the formatter is called, but this is not clear to me from the documentation.
Am I doing something wrong? If yes, could you add a note on what the expected syntax is?

Cheers

**Comment by Galarius** [comment]
Hello!

Your configuration looks fine. Could you tell me what operating system are you using and what is the version of VSCode?

`clang-format` prints result to `stderr` with `--verbose` flag. However the extension outputs to `stdout`, so you will not get any log from it. 

I have tried to use this formatter. It worked fine, however I noticed that there is no effect in the case if file was already formatted before.

**Comment by Galarius** [comment]
It would probably be better to make `clang-format` the default formatting utility instead of `astyle` and captures `stderr` output.

**Comment by definelicht** [comment]
I'm on Arch Linux, kernel version 4.20.3, clang-format version 7.0.1, Visual Code version 1.30.2.

It seems there might be an incompatibility with the Vim plugin: when I disable it, I can _occasionally_ get clang-format to work, although it seems I have to manually refresh the document to see the changes.

**Comment by Galarius** [comment]
I will update formatter in a future release. It will use `clang-format` that is built-in vscode-cpptools.
