### ISSUE TITLE
Language server

### ISSUE THREAD

**Issue by RunDevelopment** [Galarius/vscode-opencl#14]
Are there plans to add a [language server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) for OpenCL files?

Tasks are good for building kernels when you need to get the binaries but if you just want to verify that your kernel compiles, it's a bit inconvenient to manually start a task.

Unfortunately, file watchers have to be implemented by the compiler and VSC doesn't seem to provide a way to start tasks when files change. At least, I couldn't find any and [this plugin](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.triggertaskonsave) seems to confirm that.

With a language server, these compile checks can be done when a file is saved and maybe even while typing in the editor.

---

With this, it will even be possible to offer compile checks without additional tools. I believe that all Nvidia drivers come with an OpenCL compiler (all I have do), so one could just use the compiler of the GPU to check kernels.
With this, the extension will offer compiler checks out of the box for machines that support it. Not perfect in all situations but a good start.

**Comment by Galarius** [comment]
You can setup shortcuts for build tasks to run them faster. I can’t see why you need to recompile kernels on each save and especially during editing. That approach seems to be incorrect (please correct me if you think I missed the point).

**Comment by RunDevelopment** [comment]
The basic idea was to get compiler feedback like for other languages (TypeScript, Java, etc.) where you instantly get feedback while typing. The instant feedback, while CPU-heavy, is a way better editing experience IMO.

I'm sorry if I haven't made this clear before but this compiler feedback is all I care about. I don't need the binary or anything else. I just want good and convenient error/warning reporting.

Also, even though I said CPU-heavy, full compilation only takes <2sec on my laptop, so it seems feasible to recompile every, let's say, 3-5sec to get instant-ish feedback.
That being said, I don't have any experience with OpenCL compilers. Are they too slow for this kind of job (especially for a large codebase) even with `-cl-opt-disable`?

**Comment by Galarius** [comment]
OpenCL programs are often compiled at runtime and kernels are relatively small so repetitive kernel compilation when file changes may actually work.

It reminds me of an OpenGL shader editor which updates some visual effect when shader’s code is updated. Errors are also reported, if any occurs.

I would like to introduce this feature. Maybe once my other active projects are finished :)

**Comment by RunDevelopment** [comment]
Thank you for considering implementing this!
