### ISSUE TITLE
Unrecognized option flag: .spirv64

### ISSUE THREAD

**Issue by Connie120** [Galarius/vscode-opencl#20]
Hi! I was trying to build a opencl kernel on win10 but it shows this error:
![image](https://user-images.githubusercontent.com/54909364/83687155-5ada2500-a5b9-11ea-8b72-1b3166c43284.png)
Could you help me resolve this? Thanks!

**Comment by Galarius** [comment]
Hi, @Connie120! I will research this issue.

**Comment by Galarius** [comment]
@Connie120, I need to update the extension to fix this. 
Until new version is released, I suggest you to create a custom build task as a workaround:

```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558 
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "opencl: custom build [matmul_basic] {spirv64}",
            "command": "ioc64",
            "args": [
                "-cmd=build",
                "-device=gpu",
                "-input=\"d:\\CMU\\research\\exm_matmul\\matmul\\device\\matmul_basic.cl\"",
                "-spirv64=\"d:\\CMU\\research\\exm_matmul\\matmul\\device\\matmul_basic.spirv64\""
            ],
            "problemMatcher": [
                "$opencl.common"
            ],
            "group": "build"
        }
    ]
}
```

**Comment by Connie120** [comment]
I'll have a try. Thanks!

**Comment by Galarius** [comment]
@Connie120, I have updated task provider in [vscode-opencl-0.6.6](https://github.com/Galarius/vscode-opencl/releases/tag/0.6.6).
