### ISSUE TITLE
[Question] Possiblity of Visual Studio Community support?

### ISSUE THREAD

**Issue by Issung** [Galarius/vscode-opencl#23]
This addon seems like it would be great but I don't use visual studio code, only community, what's the possibility of creating a separate plugin for VS community? Would most code be reusable?

**Comment by Galarius** [comment]
@Issung, there is an official extension from Intel for VS that is a part of [OpenCL SDK](https://software.intel.com/content/www/us/en/develop/articles/sdk-for-opencl-2020-gsg-windows-os.html).
