### ISSUE TITLE
No syntax highlighting for some types (mostly unsigned)

### ISSUE THREAD

**Issue by KazNX** [Galarius/vscode-opencl#3]
The following types do not receive syntax highlighting:

uchar
ucharN
ushort
ushortN
uint
uintN
ulong
ulongN
size_t
uintptr_t
atomic_intptr_t
atomic_uintptr_t
atomic_size_t
atomic_ptrdiff_t
Note they they are recognised as auto completion keywords. The unsigned type is fine.

**Comment by Galarius** [comment]
Keywords highlighting depends on the installed color theme in VS Code. 

I noticed that it works e.g. on `Abyss`  and `Light+` themes:

<img width="697" alt="abyss" src="https://user-images.githubusercontent.com/7501085/34482802-76bd66a2-efcb-11e7-8b86-4c571364afa4.png">
<img width="696" alt="light default light" src="https://user-images.githubusercontent.com/7501085/34482803-76ef307e-efcb-11e7-9ab1-52ab87646e1d.png">

And it doesn't work e.g. on `Dark (Visual Studio)`, `Kimbie Dark` and `Light (Visual Studio)`:

<img width="698" alt="dark visual studio" src="https://user-images.githubusercontent.com/7501085/34482830-a047dc8c-efcb-11e7-9902-f7a49ac24b4e.png">
<img width="694" alt="kimbie dark" src="https://user-images.githubusercontent.com/7501085/34482832-a076233a-efcb-11e7-882e-897b59f70f11.png">
<img width="693" alt="light visual studio" src="https://user-images.githubusercontent.com/7501085/34482833-a09285e8-efcb-11e7-87c5-0e0cfe62f442.png">

Seems like some themes provides different names to identify the expression to match. I will look into it more deeply.

@KazNX What color theme do you use?

**Comment by KazNX** [comment]
@Galarius Thanks for the quick fix. I'm using the them Dark (Visual Studio) and indeed other themes are showing the syntax highlighting just fine. Your recent fix has address all the listed types except for the following, which are still not highlighting under the Dark (Visual Studio) theme:
ushort
uint
size_t
uintptr_t

**Comment by Galarius** [comment]
Those types were missed. Now they also should receive highlighting.

<img width="692" alt="dark" src="https://user-images.githubusercontent.com/7501085/34518730-c6fba784-f091-11e7-9477-9544089ab019.png">

@KazNX, the official update will be later, but you can install [`pre-release`](https://github.com/Galarius/vscode-opencl/releases/download/0.1.5-pre/vscode-opencl-0.1.5-pre.vsix) version.
