### ISSUE TITLE
Provide builds via GitHub releases

### ISSUE THREAD

**Issue by williamboman** [Galarius/vscode-opencl#34]
Hello! I'm looking at adding this language server to https://github.com/neovim/nvim-lspconfig and https://github.com/williamboman/nvim-lsp-installer for neovim users. It seems like the VSCode extension archive ships with prebuilt binaries for Linux, Windows, and Mac. I was wondering if you'd be open to publishing these `.vsix` files to the GitHub release assets, allowing for programmatic access via GitHub's REST API?

What would be even better would be if the language server itself was separated from the VSCode extension, perhaps in a separate repository with its own release pipeline. I realise this is a lot to ask for, but it'd greatly benefit non-VSCode editors!

**Comment by Galarius** [comment]
Hello, @williamboman!

OpenCL language server provides only diagnostics (compilation errors). Autocompletion, hover, and formatting are currently implemented only in a client part of the VS code extension. 

If you are still interested in adding this server to `nvim-lspconfig`, then I can start with publishing `.vsix` files to the GitHub `Releases`.

**Comment by williamboman** [comment]
> Features like completion, hover, and formatting are currently implemented only in a client part of the VS code extension.

Hm, does the server implement the LSP spec which the VSCode client then calls into (for example via `textDocument/completion` for completion)? If so, any LSP capable editor will be able to interact with the server. Or are you saying that there's a lot of features implemented in the client-side, using VSCode client APIs?

**Comment by Galarius** [comment]
> Or are you saying that there's a lot of features implemented in the client-side, using VSCode client APIs?

Yes, exactly. VSCode client API is used almost for all features. Language server supports only `textDocument/didChange` request  with `textDocument/publishDiagnostics` response.

**Comment by williamboman** [comment]
Ah I see! Well in that case it might not make much sense to make it available for other editors just yet. I'll leave it up to you to decide whether you think that functionality alone could bring value to users (to me it sounds like it could, diagnostics is very helpful) :)

**Comment by Galarius** [comment]
@williamboman, I have moved language server to a separate [repository](https://github.com/Galarius/opencl-language-server). Precompiled binaries are attached to the [release 0.1](https://github.com/Galarius/opencl-language-server/releases/tag/0.1).

**Comment by williamboman** [comment]
Oh wow that's amazing!! Thanks for your efforts, developers who doesn't use VSCode are eternally grateful :)
