### ISSUE TITLE
Add an config option for declaring defines that will be passed in at build time

### ISSUE THREAD

**Issue by LouChiSoft** [Galarius/vscode-opencl#35]
The C/C++ extension for VSCode has a feature where you can add a list of defines (and maybe their values, I have never tried it) to the c_cpp_properties.json file that it generates. IntelliSense/Syntax highlighting will then read defines and update the code as intended, greying out code that isn't going to have a define enabled etc.
It would be really useful if we could do a similar thing with this extension where we can add to a ocl_properties.json-like file all the defines that the kernels are going to be compiled with when passed to clBuildProgram etc. and have IntelliSense recognise these and highlight the defines in the code.
Apologies that this is just a suggestion and not an implementation of any kind. I have no experience with VSCode extensions outside of using them

**Comment by Galarius** [comment]
Hello, @LouChiSoft. 

There is indeed no highlighting for this case. Thank you for the suggestion.

Right now, it is only possible to pass defines to the kernel compiler.
There is `OpenCL.server.buildOptions` configuration. Build options are passed exactly to [clBuildProgram](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clBuildProgram.html).

<img width="920" alt="Screenshot 2022-02-25 at 23 21 22" src="https://user-images.githubusercontent.com/7501085/155804721-429a53b3-8be9-4b11-b996-c519d1173ff1.png">

You can set defines like this: `-D name=definition`. This will allow you to see warnings and errors only for the active fragment of code. Example:

```json
"OpenCL.server.buildOptions": [
    "-D AXIS=1"
],
```
<img width="397" alt="Screenshot 2022-02-25 at 23 45 12" src="https://user-images.githubusercontent.com/7501085/155807385-81bb48a7-4eca-4388-ad6b-d4800bc72224.png">

**Comment by LouChiSoft** [comment]
Oh cool, I hadn't populated that variable because we build our kernels at runtime so it never occurred to me that that would be a feature of that variable. Thanks
