### ISSUE TITLE
Add Code Formatter for .cl files

### ISSUE THREAD

**Issue by 24367dfa** [Galarius/vscode-opencl#4]
The package currently does not provide a code formatter for openCL files

**Comment by Galarius** [comment]
I will look into it asap. Thank you for proposing the issue!

**Comment by Galarius** [comment]
New [release](https://github.com/Galarius/vscode-opencl/releases/tag/0.3.0) is available. Added support for external formatters (e.g. [AStyle](http://astyle.sourceforge.net)).
