### ISSUE TITLE
off-line compiling

### ISSUE THREAD

**Issue by peter73421** [Galarius/vscode-opencl#5]
Is there any plans support (integrate) off-line opencl compiler ? So opencl code compiled into binary beforehand  it's use ...

**Comment by Galarius** [comment]
The plans for offline compiling support are at the very first stage. Integration of some external `clcc` utilities might appear in vscode-opencl in October.

**Comment by peter73421** [comment]
I am working with embedded device and its own opencl/openvx utilities, I assume it'll be a generic approach and so it can be customized. Since I find "vs-code and its plugin system" flexible enough to be adapted for embedded development as well.

**Comment by Galarius** [comment]
The following offline OpenCL compilers should be considered as predefined:

- [OpenCL.framework/Libraries/openclc](https://developer.apple.com/library/archive/samplecode/OpenCLOfflineCompilation/Introduction/Intro.html) (on macOS)

- [OpenCL Standalone offline compiler from `Intel® SDK for OpenCL`](https://software.intel.com/en-us/articles/programming-with-the-intel-sdk-for-opencl-applications-development-tools/) (on Linux and Windows)

**Comment by peter73421** [comment]
This would require to have Intel SDK OCL installed, would it work for Linux/Ununtu?

**Comment by Galarius** [comment]
@peter73421 I've published a preview version [0.5.0-pre](https://github.com/Galarius/vscode-opencl/releases/tag/0.5.0-pre). It introduces offline kernel compilation using [VS Code Tasks](https://code.visualstudio.com/Docs/editor/tasks). By default `ioc32/ioc64` is used on Linux/Windows and `opeclc` is used on macOS (shipped with XCode). 

It should be possible to customize build task for your own opencl/openvx utility.
I provided an [example](https://github.com/Galarius/vscode-opencl/tree/feature/taskProvider#customize-build-task) of customization process.

[vscode-opencl-0.5.0-pre.vsix](
https://github.com/Galarius/vscode-opencl/releases/download/0.5.0-pre/vscode-opencl-0.5.0-pre.vsix)

**Comment by Galarius** [comment]
Implemented in #8 .
