### ISSUE TITLE
How to include multiple .cl files

### ISSUE THREAD

**Issue by rur0** [Galarius/vscode-opencl#57]
I have a project with multiple .cl files in a single directory
When I run the opencl extension I get a load of "use of undeclared identifier" errors on vscode, because they  are defined in other files.
How can I import them so the vscode extension sees the "undeclared identifiers"?

**Comment by rur0** [comment]
> Hello @rur0, thanks for reporting this. Could you please share a minimalistic example that reproduces the same error? What platform are you using the vscode-opencl extension on?

define a function,variable, etc.. in file A.cl
reference it in file B.cl
red squiggly line appears saying "use of undeclared identifier x"

running on vscode editor

**Comment by Galarius** [comment]
There is currently no way to obtain diagnostics for multiple .cl files at once.

A possible workaround:

`A.cl`

```c
__constant int FOO = 1;
```

`B.cl`

```c
#ifdef OPENCL_DIAGNOSTICS_ENABLED
extern __constant int FOO;
#endif

__kernel void bar(__global int* pA, __global int* pB, __global int* pC)
{
    const int foo = FOO;
}
```

Add the following build option to the `settings.json` file:

```json
{
    "OpenCL.server.buildOptions": [
        "-DOPENCL_DIAGNOSTICS_ENABLED=1"
    ],
}
```

**Comment by Galarius** [comment]
Alternatively, you can restructure the code to utilize "#include" directives. This lets you declare a shared variable in a header, allowing you to obtain diagnostics without additional settings.
