### ISSUE TITLE
OpenCL 2.0 Features Not Recognized

### ISSUE THREAD

**Issue by seansiddens** [Galarius/vscode-opencl#61]
![image](https://github.com/Galarius/vscode-opencl/assets/11508260/e9f903ee-ed09-425d-9560-3c03c9037ff8)

Many OpenCL 2.0 features are marked with red squiggles and are don't appear to be recognized. Is there a way to disable this?

**Comment by Galarius** [comment]
Hi @seansiddens!  You can disable OpenCL diagnostics by setting the `OpenCL.server.enable` option to `false` (*VS Code restart is required*). However, if one of your OpenCL devices supports OpenCL 2.0, I recommend you to select the compatible device using the `OpenCL: Select` command or the corresponding action in the "Explorer: OpenCL Devices" view. Subsequently, set `-cl-std=CL2.0` in the `OpenCL.server.buildOptions` setting. This will keep diagnostics enabled while supporting OpenCL 2.0 features.

**Comment by seansiddens** [comment]
Thanks! Setting the build option seems to have worked 👍
