### ISSUE TITLE
no matching function call to 'read_imagef'

### ISSUE THREAD

**Issue by abibibu** [Galarius/vscode-opencl#67]
Hello, I have installed this Extension via vs code extension tab, it works but not entirely: i.e. intellisense suggest read_imagef but then I get the above error, I have the AMD runtime and the intel sdk installed.

**Comment by abibibu** [comment]
![image](https://github.com/Galarius/vscode-opencl/assets/49687371/c4c01369-5a39-4f02-bfdb-770be9f3a8e5)

**Comment by abibibu** [comment]
and it does not happen for every function, for example get_global_id() works fine.

**Comment by Galarius** [comment]
Hello @abibibu! Enabling a specific extension may help, but unfortunately, I cannot specify which one. It greatly depends on the OpenCL device.

1. Please try to set `"OpenCL.server.debug.enableFileLogging": true` in your workspace settings.

   ![Screenshot 2024-02-27 at 20 42 07](https://github.com/Galarius/vscode-opencl/assets/7501085/6d588cca-944d-4c1b-908e-c1585de2bf00)

2. Restart VS Code.
3. Reproduce the issue.
4. Retrieve the `opencl-language-server.log` file.
5. Look for records containing `[diagnostics]` for additional details.
6. You can also share the log with me if you think it is safe (file paths are not anonymized).

**Comment by Galarius** [comment]
Typically, the error `no matching function call to` indicates that the function expects arguments of different types.

**Comment by Galarius** [comment]
According to the OpenCL [documentation](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/imageReadFunctions.html), the function `float read_imagef(read_only image2d_depth_t image, sampler_t sampler, float2 coord)` requires OpenCL C 2.0 or newer and the `cl_khr_depth_images` extension. Please enable the extension with this pragma at the beginning of the source file:

```c
#pragma OPENCL EXTENSION cl_khr_depth_images : enable
```

To activate OpenCL 2.0, add `-cl-std=CL2.0` to the `OpenCL.server.buildOptions` setting.

![Screenshot 2024-02-27 at 22 41 12](https://github.com/Galarius/vscode-opencl/assets/7501085/1caec859-7e7d-4711-8b86-2c9d5ee61551)

**Comment by abibibu** [comment]
> According to the OpenCL [documentation](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/imageReadFunctions.html), the function `float read_imagef(read_only image2d_depth_t image, sampler_t sampler, float2 coord)` requires OpenCL C 2.0 or newer and the `cl_khr_depth_images` extension. Please enable the extension with this pragma at the beginning of the source file:
> 
> ```c
> #pragma OPENCL EXTENSION cl_khr_depth_images : enable
> ```
> 
> To activate OpenCL 2.0, add `-cl-std=CL2.0` to the `OpenCL.server.buildOptions` setting.
> 
> ![Screenshot 2024-02-27 at 22 41 12](https://private-user-images.githubusercontent.com/7501085/308330499-1caec859-7e7d-4711-8b86-2c9d5ee61551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDk3MjYsIm5iZiI6MTcwOTEwOTQyNiwicGF0aCI6Ii83NTAxMDg1LzMwODMzMDQ5OS0xY2FlYzg1OS03ZTdkLTQ3MTEtOGI4Ni0yYzlkNWVlNjE1NTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDgzNzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBkYzdkZjVkOGM5NjBmMDE4OWQzZTA3ZjUzOTYwZWEwMDJiMWVmYWY2MTM5N2IzNDk5NzhhZTYyYzBhOWUzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8BtxMqsthV9GJYjifMlltrAAfoFC-4HLzL66H0Ccdig)

ok this works, thanks, all the errors at function calls are gone now but I still have this one:
![image](https://github.com/Galarius/vscode-opencl/assets/49687371/73977120-f079-4772-9d5d-ebcc8a9d259e)

here is the log
[opencl-language-server.log](https://github.com/Galarius/vscode-opencl/files/14431246/opencl-language-server.log)

**Comment by abibibu** [comment]
also when I launch OpenCL:select I get this error: 
![image](https://github.com/Galarius/vscode-opencl/assets/49687371/54929d16-0508-466c-af92-089ba9be538b)

in this case the log does not seem to register anything

**Comment by Galarius** [comment]
> ok this works, thanks, all the errors at function calls are gone now but I still have this one:

It seems that this extension should be enabled by default:

> All of the cl_khr_* extensions from [the official OpenCL specification](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/EXTENSION.html) up to and including version 2.0 are available and set per target depending on the support available in the specific architecture.
(https://releases.llvm.org/9.0.1/tools/clang/docs/UsersManual.html)

If not, then perhaps this build flag can help:
 
> It is possible to alter the default extensions setting per target using -cl-ext flag. (See [flags description](https://releases.llvm.org/9.0.1/tools/clang/docs/UsersManual.html#opencl-cl-ext) for more details).

**Comment by Galarius** [comment]
> also when I launch OpenCL:select I get this error: ![image](https://private-user-images.githubusercontent.com/49687371/308484765-54929d16-0508-466c-af92-089ba9be538b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzczNTcsIm5iZiI6MTcwOTIzNzA1NywicGF0aCI6Ii80OTY4NzM3MS8zMDg0ODQ3NjUtNTQ5MjlkMTYtMDUwOC00NjZjLWFmOTItMDg5YmE5YmU1MzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDIwMDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDg4MWU1Y2YxN2EzNjUyNjFhYjE1NDZiYmZmZWUzOGViNmZmOGE5OTYyNzk0MzExNmNjOGJkMmU3NmJiZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rp2bsDEedxluPUMoxgxYKi_aEPrzpLdAn6Dv7Tqwf1I)
> 
> in this case the log does not seem to register anything

This looks like an error in the extension, however I can see in the [opencl-language-server.log](https://github.com/Galarius/vscode-opencl/files/14431246/opencl-language-server.log) that there should be at least one platform. Do you see your OpenCL platform and devices in the Explorer view ?

<img width="541" alt="Screenshot 2024-02-29 at 22 23 08" src="https://github.com/Galarius/vscode-opencl/assets/7501085/2a429e8b-bf2d-4b1c-968b-daa8967169d1">

("OpenCL Devices" panel could be located in another side view)

**Comment by abibibu** [comment]
> > also when I launch OpenCL:select I get this error: ![image](https://private-user-images.githubusercontent.com/49687371/308484765-54929d16-0508-466c-af92-089ba9be538b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzczNTcsIm5iZiI6MTcwOTIzNzA1NywicGF0aCI6Ii80OTY4NzM3MS8zMDg0ODQ3NjUtNTQ5MjlkMTYtMDUwOC00NjZjLWFmOTItMDg5YmE5YmU1MzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDIwMDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDg4MWU1Y2YxN2EzNjUyNjFhYjE1NDZiYmZmZWUzOGViNmZmOGE5OTYyNzk0MzExNmNjOGJkMmU3NmJiZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rp2bsDEedxluPUMoxgxYKi_aEPrzpLdAn6Dv7Tqwf1I)
> > in this case the log does not seem to register anything
> 
> This looks like an error in the extension, however I can see in the [opencl-language-server.log](https://github.com/Galarius/vscode-opencl/files/14431246/opencl-language-server.log) that there should be at least one platform. Do you see your OpenCL platform and devices in the Explorer view ?
> 
> <img alt="Screenshot 2024-02-29 at 22 23 08" width="541" src="https://private-user-images.githubusercontent.com/7501085/309063927-2a429e8b-bf2d-4b1c-968b-daa8967169d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNDk2MDgsIm5iZiI6MTcwOTI0OTMwOCwicGF0aCI6Ii83NTAxMDg1LzMwOTA2MzkyNy0yYTQyOWU4Yi1iZjJkLTRiMWMtOTY4Yi1kYWE4OTY3MTY5ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMjMyODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTY4MjkyZTU1YWM4OGYwZjlkMjg4NDM1ZmJmYzFhOGU4Y2QxYmI3N2QxMzdjNzBmYjFjNDVmMzc2YmZkOThmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dVT43R5dtwuz9aN_D3cAnZiOEVQYvC6cx6dnKFyDxds">
> ("OpenCL Devices" panel could be located in another side view)

No, I don't see either OpenCL devices nor openCL language server, I saw that there is a repos named open cl language server but I haven't installed it, should I?

**Comment by Galarius** [comment]
`vscode-opencl` extension is shipped with `opencl-language-server` which provides intellisense and hardware information. Also [opencl-language-server.log](https://github.com/Galarius/vscode-opencl/files/14431246/opencl-language-server.log) was produced by the language server, so it should already be installed.

**Comment by abibibu** [comment]
![image](https://github.com/Galarius/vscode-opencl/assets/49687371/2afddf94-fb34-4a3f-a6e6-56bf9d6b3e2b)

Now the error on OpenCL:Select is gone and I see OPENCL DEVICES, maybe a restart did the thing, sorry for the bother.

Now the only thing is that intellisense for get_global_id() shows all infos but for read_imagef() shows only "OpenCl built in function" should it be like that?

**Comment by abibibu** [comment]
Perfect, thank you very much, this extension is really helpful.
Have a nice day.
