### ISSUE TITLE
An error occurred when I was using OpenCl device

### ISSUE THREAD

**Issue by w-y-z** [Galarius/vscode-opencl#68]
Unexpected token ':', "t: Command "... is not valid JSON
[Error: 3221226505]
![059b08dd2b3e744e0da4acdbf2b27f5](https://github.com/Galarius/vscode-opencl/assets/70888048/010836e4-e0bb-4a0b-9ccb-8525c2b20db9)

**Comment by Galarius** [comment]
Hi @w-y-z, please provide some information about your environment: 

* platform (macOS, linux, windows) 
* arch (x86_64, arm64)
* virtual machine or a real device
* VS code version and vscode-opencl extension version

Please also enable file logging (as shown below), then restart VS Code and repeat the steps that caused the issue. Finally, please send me `opencl-language-server.log`.

![Screenshot 2024-05-13 at 21 32 54](https://github.com/Galarius/vscode-opencl/assets/7501085/ec60f7a7-f99d-41dd-bdb3-c31152557c4a)

**Comment by w-y-z** [comment]
Hello, some of my information is as follows
platform:linux and windows
arch:x86_64
real device
vscode 1.89.1 and vscode-opencl v0.8.3

**Comment by w-y-z** [comment]
[opencl-language-server.log](https://github.com/Galarius/vscode-opencl/files/15416062/opencl-language-server.log)

**Comment by Galarius** [comment]
Unfortunately, some output wasn't flushed to the log file. To ensure the entire output is captured, the process needs to be terminated (I'll try to improve it in the future release). In the meantime, let's narrow down the scope of the error. The vscode-opencl project consists of a VSCode extension and a language server. Could you please run the language server manually with the following command:

`<VS Code Installation Directory>/extensions/galarius.vscode-opencl-0.8.3/bin/win32/opencl-language-server.exe -e clinfo`

The default installation directory is likely `C:\Users\{UserName}\AppData\Local\Programs\Microsoft VS Code.`

The stdout should contain information about OpenCL platforms and devices in JSON format. Additionally, an `opencl-language-server.log` file will be generated in the current directory. If the JSON is malformed, we can hopefully catch some errors here.

**Comment by Galarius** [comment]
Hey @w-y-z,

The fix has been included in the vscode-opencl 0.8.5 release:

* https://github.com/Galarius/vscode-opencl/releases/tag/0.8.5
* https://marketplace.visualstudio.com/items?itemName=galarius.vscode-opencl
* https://open-vsx.org/extension/galarius/vscode-opencl
