### ISSUE TITLE
predefined tasks

### ISSUE THREAD

**Issue by manuliner** [Galarius/vscode-opencl#9]
Hello,

i can't find your predefined tasks.

may i ask you to provide them seperately so i can just paste them into my task.json

runnning on win 10

**Comment by Galarius** [comment]
Hello!

An example of a build task:

![](https://raw.githubusercontent.com/Galarius/vscode-opencl/master/images/vscode-opencl-clc-3.png)


The extension generates tasks for each detected .cl file in a project directory. Do you have a kernel file inside your project which is opened in VS Code?

**Comment by manuliner** [comment]
there is no task.json generated by the extension

![screenshot 2018-12-18 13 18 59](https://user-images.githubusercontent.com/5088151/50153798-bfbb9580-02c7-11e9-8e0b-ade1ba37321e.png)

**Comment by manuliner** [comment]
fyi: 

the predfined task is working without the spriv64 argument

**Comment by Galarius** [comment]
Not yet, but I’ll look into it.

**Comment by Galarius** [comment]
I’ve noticed that you are using command palette instead of a task runner on your screenshot.

Please try to run predefined tasks from the Task menu (see the screenshot). 

![](https://raw.githubusercontent.com/Galarius/vscode-opencl/master/images/vscode-opencl-clc-1.png)

**Comment by Galarius** [comment]
In your version of VS Code Task menu was renamed to Terminal.

**Comment by manuliner** [comment]
there is no Tasks menu on the menubar

if i go over terminal->run tasks the inputfield opens and tells me that ther are no defined task, if i want to build some.
- i prompt this and get redirected to the next inputfield to create task.json from template
- options: MSBuild, maven, .NETCore and others

**Comment by Galarius** [comment]
I reproduced the issue. Tasks are still being generated, but are not displayed in the latest VS Code version.

**Comment by Galarius** [comment]
Fixed it! The release is coming soon...

**Comment by Galarius** [comment]
[Release 0.5.1](https://github.com/Galarius/vscode-opencl/releases/tag/0.5.1) is available in Marketplace.

**Comment by manuliner** [comment]
cool, 
it is working now

thank you very much . Love it

**Comment by Shogutora** [comment]
VSCode release 1.31 Broke this again. Just updated today and tasks are lost from the menu.

**Comment by Galarius** [comment]
Yes, something is broken again, I will look into it.

**Comment by Galarius** [comment]
According to [vscode/issues/67990](https://github.com/Microsoft/vscode/issues/67990) the introduced fix for VS Code ^1.31.0 is incompatible with older releases.

**Comment by Galarius** [comment]
[Release 0.5.2](https://github.com/Galarius/vscode-opencl/releases/tag/0.5.2) is available in Marketplace.

**Comment by Galarius** [comment]
Does not work for VS Code 1.32.1.

**Comment by Galarius** [comment]
False alert
